#sub_path_only rewrite ^__PATH__$ __PATH__/ permanent;
location __PATH__/ {

  proxy_pass       http://localhost:__PORT__;

  include proxy_params_no_auth;
  proxy_set_header X-Script-Name __PATH__/;
}
